name: "Publish Artifacts"

on:
  push:
    branches:
      - master

permissions:
  actions: write
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/install-gradle.yml
    with:
      gradle-command-title: "Publish"
      gradle-command: "publish"
