name: "Publish"

on:
  push:
    branches:
      - master

permissions:
  actions: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      - name: "Publish"
        uses: ./.github/actions/install-gradle
        with:
          gradle-command: "publish"
