name: "Run Gradle Build"
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

permissions:
  actions: write
  contents: read

jobs:
  build:
    uses: ./.github/workflows/install-gradle.yml
    with:
      gradle-command-title: "Build with JDK ${{ matrix.java }} on ${{ matrix.os }}"
      gradle-command: "build"
